### PR TITLE
Stefano 3 11 20

### PR DESCRIPTION
**Pull request by ninedesign**
Before merging, let's talk so I can explain what was happening and why. Thanks!

### CODE REVIEW

**Comment by littlejohnjt** [comment]
Do you have time this evening either before 7:00 ET or after 8:30 ET?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ninedesign** [comment]
Hi Todd, I have time for a short call before 7pm EST as I have class at 8pm EST and for the following 3,5 hours.

Let me know thanks.

—
Stefano Bossi
970.690.7830

**Comment by littlejohnjt** [comment]
Im in the middle of testing a fix for something.  If I can get it working and submitted for peer review I’ll message you.  Perhaps I can do it earlier.  I’ll keep you posted.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ninedesign** [comment]
Sounds good :)

—
Stefano Bossi
970.690.7830

**Review by littlejohnjt — APPROVED** [review]

**Pull request merged**
